FROM confluentinc/cp-kafka:7.7.1

USER root

ARG JMX_EXPORTER_VERSION=1.0.1
ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${JMX_EXPORTER_VERSION}/jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar /opt/jmx-exporter/jmx_prometheus_javaagent.jar
COPY config/jmx-exporter.yml /opt/jmx-exporter/config.yml
RUN chmod 0644 /opt/jmx-exporter/jmx_prometheus_javaagent.jar /opt/jmx-exporter/config.yml

USER appuser

